-- 1. Categories Table
create table categories (
  id bigint primary key generated by default as identity,
  name text not null,
  description text,
  icon_name text default 'restaurant',
  product_count int default 0,
  user_id uuid references auth.users not null default auth.uid()
);

-- 2. Products Table
create table products (
  id bigint primary key generated by default as identity,
  category_id bigint references categories(id) on delete cascade,
  name text not null,
  price double precision not null,
  cogs double precision default 0.0,
  stock int,
  image_path text,
  is_new boolean default false,
  created_at bigint default extract(epoch from now()) * 1000,
  user_id uuid references auth.users not null default auth.uid()
);

-- 3. Orders Table
create table orders (
  id bigint primary key generated by default as identity,
  order_number text not null,
  status text not null, -- QUEUE, PROCESS, DONE, ARCHIVED
  total_items int default 0,
  total_price double precision default 0.0,
  customer_name text,
  table_info text,
  created_at bigint default extract(epoch from now()) * 1000,
  updated_at bigint default extract(epoch from now()) * 1000,
  user_id uuid references auth.users not null default auth.uid()
);

-- 4. Order Items Table
create table order_items (
  id bigint primary key generated by default as identity,
  order_id bigint references orders(id) on delete cascade,
  product_id bigint references products(id) on delete cascade,
  product_name text not null,
  quantity int not null,
  unit_price double precision not null,
  cogs double precision default 0.0,
  total_price double precision not null,
  net_income double precision default 0.0,
  user_id uuid references auth.users not null default auth.uid()
);

-- 5. Expenses Table
create table expenses (
  id bigint primary key generated by default as identity,
  title text not null,
  amount double precision not null,
  category text not null,
  note text,
  date bigint default extract(epoch from now()) * 1000,
  created_at bigint default extract(epoch from now()) * 1000,
  user_id uuid references auth.users not null default auth.uid()
);

-- 6. Transactions Table
create table transactions (
  id bigint primary key generated by default as identity,
  order_id bigint references orders(id) on delete cascade,
  order_number text not null,
  payment_method text not null, -- CASH, TRANSFER, QRIS
  subtotal double precision not null,
  tax double precision default 0.0,
  total_amount double precision not null,
  total_cogs double precision default 0.0,
  net_income_total double precision default 0.0,
  amount_paid double precision not null,
  change_amount double precision default 0.0,
  bank_name text,
  customer_name text,
  status text default 'Success',
  is_refunded boolean default false,
  created_at bigint default extract(epoch from now()) * 1000,
  user_id uuid references auth.users not null default auth.uid()
);

-- Enable RLS (Row Level Security)
alter table categories enable row level security;
alter table products enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table expenses enable row level security;
alter table transactions enable row level security;

-- Create Policies for Authenticated Users
-- Categories
create policy "category_select" on categories for select to authenticated using (auth.uid() = user_id);
create policy "category_insert" on categories for insert to authenticated with check (auth.uid() = user_id);
create policy "category_update" on categories for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "category_delete" on categories for delete to authenticated using (auth.uid() = user_id);

-- Products
create policy "product_select" on products for select to authenticated using (auth.uid() = user_id);
create policy "product_insert" on products for insert to authenticated with check (auth.uid() = user_id);
create policy "product_update" on products for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "product_delete" on products for delete to authenticated using (auth.uid() = user_id);

-- Orders
create policy "order_select" on orders for select to authenticated using (auth.uid() = user_id);
create policy "order_insert" on orders for insert to authenticated with check (auth.uid() = user_id);
create policy "order_update" on orders for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "order_delete" on orders for delete to authenticated using (auth.uid() = user_id);

-- Order Items
create policy "order_item_select" on order_items for select to authenticated using (auth.uid() = user_id);
create policy "order_item_insert" on order_items for insert to authenticated with check (auth.uid() = user_id);
create policy "order_item_update" on order_items for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "order_item_delete" on order_items for delete to authenticated using (auth.uid() = user_id);

-- Expenses
create policy "expense_select" on expenses for select to authenticated using (auth.uid() = user_id);
create policy "expense_insert" on expenses for insert to authenticated with check (auth.uid() = user_id);
create policy "expense_update" on expenses for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "expense_delete" on expenses for delete to authenticated using (auth.uid() = user_id);

-- Transactions
create policy "transaction_select" on transactions for select to authenticated using (auth.uid() = user_id);
create policy "transaction_insert" on transactions for insert to authenticated with check (auth.uid() = user_id);
create policy "transaction_update" on transactions for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "transaction_delete" on transactions for delete to authenticated using (auth.uid() = user_id);

-- 7. Customers Table
create table customers (
  id bigint primary key generated by default as identity,
  name text not null,
  phone text,
  email text,
  address text,
  created_at bigint default extract(epoch from now()) * 1000,
  updated_at bigint default extract(epoch from now()) * 1000,
  user_id uuid references auth.users not null default auth.uid()
);

-- Note: orders and transactions tables need modification in existing deployment
-- alter table orders add column customer_id bigint references customers(id) on delete set null;
-- alter table transactions add column customer_id bigint references customers(id) on delete set null;

-- Enable RLS for Customers
alter table customers enable row level security;

-- Policies for Customers
create policy "customer_select" on customers for select to authenticated using (auth.uid() = user_id);
create policy "customer_insert" on customers for insert to authenticated with check (auth.uid() = user_id);
create policy "customer_update" on customers for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "customer_delete" on customers for delete to authenticated using (auth.uid() = user_id);

-- COGS (HPP) Migration
alter table products add column if not exists cogs double precision default 0.0;
alter table order_items add column if not exists cogs double precision default 0.0;
alter table transactions add column if not exists total_cogs double precision default 0.0;
alter table order_items add column if not exists net_income double precision default 0.0;
alter table transactions add column if not exists net_income_total double precision default 0.0;
