
-- 7. Customers Table
create table customers (
  id bigint primary key generated by default as identity,
  name text not null,
  phone text,
  email text,
  address text,
  created_at bigint default extract(epoch from now()) * 1000,
  updated_at bigint default extract(epoch from now()) * 1000,
  user_id uuid references auth.users not null default auth.uid()
);

-- Add customer_id to Orders
alter table orders add column customer_id bigint references customers(id) on delete set null;
alter table orders add column customer_name text;

-- Add customer_id to Transactions
alter table transactions add column customer_id bigint references customers(id) on delete set null;
-- transactions already has customer_name

-- Enable RLS for Customers
alter table customers enable row level security;

-- Policies for Customers
create policy "customer_select" on customers for select to authenticated using (auth.uid() = user_id);
create policy "customer_insert" on customers for insert to authenticated with check (auth.uid() = user_id);
create policy "customer_update" on customers for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "customer_delete" on customers for delete to authenticated using (auth.uid() = user_id);
